### ISSUE TITLE
BufferUnderflowException when attempting to install from snapshot

### ISSUE THREAD

**Issue by madjam** [atomix/copycat#162]
Noticed the following exception
```
2016-02-19 22:26:47,757 | INFO  | 0.254.1.203:9876 | ServerStateMachine  | 10.254.1.203/10.254.1.203:9876 - Installing snapshot 3902239
2016-02-19 22:26:47,759 | ERROR | 203:9876-state-1 | SingleThreadContext  | An uncaught exception occurred
java.nio.BufferUnderflowException
	at io.atomix.catalyst.buffer.AbstractBuffer.checkRead(AbstractBuffer.java:371)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.catalyst.buffer.AbstractBuffer.checkRead(AbstractBuffer.java:351)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.catalyst.buffer.AbstractBuffer.readLong(AbstractBuffer.java:578)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.storage.snapshot.SnapshotReader.readLong(SnapshotReader.java:151)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.variables.state.LongState.install(LongState.java:46)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.manager.state.ResourceManagerState.install(ResourceManagerState.java:81)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.ServerStateMachine.lambda$installSnapshot$82(ServerStateMachine.java:124)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.ServerStateMachine$$Lambda$587/1905889655.run(Unknown Source)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.catalyst.util.concurrent.Runnables.lambda$logFailure$17(Runnables.java:20)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.catalyst.util.concurrent.Runnables$$Lambda$49/1217411637.run(Unknown Source)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_31]
```
Not immediately clear what happened here.

**Comment by kuujo** [comment]
Hmmm...

**Comment by madjam** [comment]
There appears to be an issue with how the data field (of type `Buffer`) in `InstallRequest` gets serialized and resurrected.

At `LEADER`:
```
Sent InstallRequest[term=2, leader=-1062706609, index=66421, offset=0, data=HeapBuffer[position=0, limit=176], complete=true] to 192.168.56.101/192.168.56.101:9876
```
At `FOLLOWER`:
```
Received InstallRequest[term=2, leader=-1062706609, index=66421, offset=0, data=HeapBuffer[position=0, limit=0], complete=true]
```
At first glance it is not clear to me why it is happening. If I change the type of the `data` field from `Buffer` to `byte[]` in `InstallRequest`, it works fine.

**Comment by kuujo** [comment]
Hmm... Maybe should use byte[] just to be safe and can look at the Buffer serializer separately

**Comment by madjam** [comment]
That sounds good to me. I'll open a pull request for that shortly
