### ISSUE TITLE
IndexOutOfBoundsException on a Log::get

### ISSUE THREAD

**Issue by madjam** [atomix/copycat#185]
Noticed this with latest copycat. Logging an issue so that I don't miss it.
```
2016-03-06 21:36:18,479 | ERROR | 9876-partition-3 | SingleThreadContext              | 68 - org.onosproject.onlab-thirdparty - 1.5.0.SNAPSHOT | An uncaught exception occurred
java.lang.IndexOutOfBoundsException
	at io.atomix.catalyst.buffer.util.BitArray.get(BitArray.java:97)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.storage.util.OffsetPredicate.test(OffsetPredicate.java:53)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.storage.Segment.isLive(Segment.java:442)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.storage.Log.get(Log.java:371)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.AbstractAppender.getPrevEntry(AbstractAppender.java:220)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.AbstractAppender.buildAppendEntriesRequest(AbstractAppender.java:164)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.AbstractAppender.buildAppendRequest(AbstractAppender.java:134)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.LeaderAppender.appendEntries(LeaderAppender.java:206)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.LeaderAppender.appendEntries(LeaderAppender.java:110)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.LeaderState.appendMembers(LeaderState.java:143)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.LeaderState$$Lambda$189/637399727.run(Unknown Source)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.catalyst.util.concurrent.Runnables.lambda$logFailure$0(Runnables.java:20)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.catalyst.util.concurrent.Runnables$$Lambda$52/42728993.run(Unknown Source)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_31]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_31]
```

**Comment by kuujo** [comment]
It looks like the condition for checking the bit array in `OffsetPredixate.test` is just one index off:

```
bits.size() < offset
```

`offset` is zero-based, so the condition should be `bits.size() <= offset`. If there are `16` bits in the bit array, and the `offset` is `16`, you'll get `IndexOutOfBoundsException`.
