### ISSUE TITLE
failure in building 

### ISSUE THREAD

**Issue by vipulg** [atomix/copycat#245]
Tests run: 762, Failures: 5, Errors: 0, Skipped: 7, Time elapsed: 97.949 sec <<< FAILURE! - in TestSuite
testDeleteMetaStore(io.atomix.copycat.server.storage.MetaStoreTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
        at io.atomix.copycat.server.storage.MetaStoreTest.testDeleteMetaStore(MetaStoreTest.java:115)

cleanupStorage(io.atomix.copycat.server.storage.MetaStoreTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.nio.file.FileSystemException:
target\test-logs\6f8c443b-ee71-44be-a5c6-a712c25b62c8\test.meta: The process cannot access the file because it is being used by another process.

        at io.atomix.copycat.server.storage.MetaStoreTest.cleanupStorage(MetaStoreTest.java:124)

testDescriptorBuilder(io.atomix.copycat.server.storage.SegmentDescriptorTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected [1471098231940] but found [0]
        at io.atomix.copycat.server.storage.SegmentDescriptorTest.testDescriptorBuilder(SegmentDescriptorTest.java:58)

deleteDescriptor(io.atomix.copycat.server.storage.SegmentDescriptorTest)  Time elapsed: 0 sec  <<< FAILURE!
java.nio.file.FileSystemException:
descriptor.log: The process cannot access the file because it is being used by another process.

        at io.atomix.copycat.server.storage.SegmentDescriptorTest.deleteDescriptor(SegmentDescriptorTest.java:127)

cleanLogDir(io.atomix.copycat.server.storage.MappedLogTest)  Time elapsed: 0 sec  <<< FAILURE!
java.nio.file.FileSystemException:
target\test-logs\6f8c443b-ee71-44be-a5c6-a712c25b62c8\test.meta: The process cannot access the file because it is being used by another process.

Results :

Failed tests:
  MappedLogTest>AbstractLogTest.cleanLogDir:124 » FileSystem target\test-logs\6f...
io.atomix.copycat.server.storage.MetaStoreTest.cleanupStorage(io.atomix.copycat.server.storage.MetaStoreTest)
  Run 1: MetaStoreTest.cleanupStorage:124 » FileSystem target\test-logs\6f8c443b-ee71-4...
  Run 2: PASS
  Run 3: PASS

  MetaStoreTest.testDeleteMetaStore:115 expected [0] but found [1]
io.atomix.copycat.server.storage.SegmentDescriptorTest.deleteDescriptor(io.atomix.copycat.server.storage.SegmentDescriptorTest)
  Run 1: SegmentDescriptorTest.deleteDescriptor:127 » FileSystem descriptor.log: The pr...
  Run 2: PASS
  Run 3: PASS

  SegmentDescriptorTest.testDescriptorBuilder:58 expected [1471098231940] but found [0]

Tests run: 758, Failures: 5, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Copycat Parent Pom ................................. SUCCESS [  3.008 s]
[INFO] Copycat Protocol ................................... SUCCESS [ 13.079 s]
[INFO] Copycat Server ..................................... FAILURE [01:44 min]
[INFO] Copycat Client ..................................... SKIPPED
[INFO] Copycat Raft Tests ................................. SKIPPED
[INFO] Copycat Examples Parent ............................ SKIPPED
[INFO] Copycat State Machine Example ...................... SKIPPED
[INFO] Copycat Client Example ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:02 min
[INFO] Finished at: 2016-08-13T19:54:03+05:30
[INFO] Final Memory: 37M/582M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project copycat-server: There are test failures.
[ERROR]
[ERROR] Please refer to C:\vipul\git\raft\copycat\server\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :copycat-server

**Comment by maguro** [comment]
This builds fine for me.  Could supply additional information on how to reproduce the error:

- OS version
- Java verison
- mvn version

Does this error occur for you on other machines?

**Comment by vipulg** [comment]
Hi Alan,

OS - Windows 10
Java - build 1.8.0_92-b14
mvn - Apache Maven 3.3.9

I am still seeing this error on trying to build server

20:48:19.283 [test-server] DEBUG i.a.c.s.storage.system.MetaStore - Store
configuration Configuration[index=0, time=1471274299283,
members=[ServerMember[type=ACTIVE, status=AVAILABLE,
serverAddress=localhost/127.0.0.1:5000, c
lientAddress=localhost/127.0.0.1:6000], ServerMember[type=ACTIVE,
status=AVAILABLE, serverAddress=localhost/127.0.0.1:5001,
clientAddress=localhost/127.0.0.1:6001], ServerMember[type=ACTIVE,
status=AVAILABLE, serverAddress=lo
calhost/127.0.0.1:5002, clientAddress=localhost/127.0.0.1:6002]]]
20:48:19.284 [test-server] DEBUG i.a.c.server.state.PassiveState -
localhost/127.0.0.1:5000 - Received VoteRequest[term=1, candidate=1,
logIndex=1, logTerm=1]
20:48:19.285 [test-server] DEBUG i.a.c.s.storage.system.MetaStore - Store
term 1
20:48:19.285 [test-server] DEBUG i.a.c.s.storage.system.MetaStore - Store
vote 0
20:48:19.285 [test-server] DEBUG i.a.c.server.state.ServerContext -
localhost/127.0.0.1:5000 - Set term 1
20:48:19.285 [test-server] DEBUG i.a.c.server.state.PassiveState -
localhost/127.0.0.1:5000 - Sent VoteResponse[status=ERROR, term=0,
voted=false]
Tests run: 762, Failures: 5, Errors: 0, Skipped: 7, Time elapsed: 100.114
sec <<< FAILURE! - in TestSuite
testDeleteMetaStore(io.atomix.copycat.server.storage.MetaStoreTest)  Time
elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
        at
io.atomix.copycat.server.storage.MetaStoreTest.testDeleteMetaStore(MetaStoreTest.java:115)

cleanupStorage(io.atomix.copycat.server.storage.MetaStoreTest)  Time
elapsed: 0.005 sec  <<< FAILURE!
java.nio.file.FileSystemException:
target\test-logs\0640466a-3a00-4427-b03f-5c18f1601ab8\test.meta: The
process cannot access the file because it is being used by another process.

        at
io.atomix.copycat.server.storage.MetaStoreTest.cleanupStorage(MetaStoreTest.java:124)

testDescriptorBuilder(io.atomix.copycat.server.storage.SegmentDescriptorTest)
 Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected [1471274299290] but found [0]
        at
io.atomix.copycat.server.storage.SegmentDescriptorTest.testDescriptorBuilder(SegmentDescriptorTest.java:58)

deleteDescriptor(io.atomix.copycat.server.storage.SegmentDescriptorTest)
 Time elapsed: 0 sec  <<< FAILURE!
java.nio.file.FileSystemException:
descriptor.log: The process cannot access the file because it is being used
by another process.

        at
io.atomix.copycat.server.storage.SegmentDescriptorTest.deleteDescriptor(SegmentDescriptorTest.java:127)

cleanLogDir(io.atomix.copycat.server.storage.MappedLogTest)  Time elapsed:
0 sec  <<< FAILURE!
java.nio.file.FileSystemException:
target\test-logs\0640466a-3a00-4427-b03f-5c18f1601ab8\test.meta: The
process cannot access the file because it is being used by another process.



Results :

Failed tests:
  MappedLogTest>AbstractLogTest.cleanLogDir:124 » FileSystem
target\test-logs\06...
io.atomix.copycat.server.storage.MetaStoreTest.cleanupStorage(io.atomix.copycat.server.storage.MetaStoreTest)
  Run 1: MetaStoreTest.cleanupStorage:124 » FileSystem
target\test-logs\0640466a-3a00-4...
  Run 2: PASS
  Run 3: PASS

  MetaStoreTest.testDeleteMetaStore:115 expected [0] but found [1]
io.atomix.copycat.server.storage.SegmentDescriptorTest.deleteDescriptor(io.atomix.copycat.server.storage.SegmentDescriptorTest)
  Run 1: SegmentDescriptorTest.deleteDescriptor:127 » FileSystem
descriptor.log: The pr...
  Run 2: PASS
  Run 3: PASS

  SegmentDescriptorTest.testDescriptorBuilder:58 expected [1471274299290]
but found [0]

Tests run: 758, Failures: 5, Errors: 0, Skipped: 3

[INFO]
------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Copycat Parent Pom ................................. SUCCESS [
 3.900 s]
[INFO] Copycat Protocol ................................... SUCCESS [
12.889 s]
[INFO] Copycat Server ..................................... FAILURE [01:47
min]
[INFO] Copycat Client ..................................... SKIPPED
[INFO] Copycat Raft Tests ................................. SKIPPED
[INFO] Copycat Examples Parent ............................ SKIPPED
[INFO] Copycat State Machine Example ...................... SKIPPED
[INFO] Copycat Client Example ............................. SKIPPED
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 02:06 min
[INFO] Finished at: 2016-08-15T20:48:31+05:30
[INFO] Final Memory: 32M/418M
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test)
on project copycat-server: There are test failures.
[ERROR]

-Vipul
