### ISSUE TITLE
failing tests while building from trunk 

### ISSUE THREAD

**Issue by vipulg** [atomix/copycat#246]
io.atomix.copycat.server.storage.MetaStoreTest
testDeleteMetaStore
java.lang.AssertionError: expected [0] but found [1]
	at io.atomix.copycat.server.storage.MetaStoreTest.testDeleteMetaStore(MetaStoreTest.java:115)
... Removed 33 stack frames
 io.atomix.copycat.server.storage.SegmentDescriptorTest

testDescriptorBuilder
java.lang.AssertionError: expected [1471100967532] but found [0]
	at io.atomix.copycat.server.storage.SegmentDescriptorTest.testDescriptorBuilder(SegmentDescriptorTest.java:58)
... Removed 33 stack frames

**Comment by maguro** [comment]
This builds fine for me. Could supply additional information on how to reproduce the error:

- OS version
- Java verison
- mvn version
Does this error occur for you on other machines?
