### ISSUE TITLE
SerializationException

### ISSUE THREAD

**Issue by qinjin** [atomix/copycat#66]
Hi,

When I started 3 CopycatServer locally, got the following exceptions. 
Any idea on this?
Thanks!

```Java
16:21:04.880 [copycat-server-Address[localhost/127.0.0.1:8521]] ERROR i.a.c.u.c.SingleThreadContext - An uncaught exception occurred
io.atomix.catalyst.serializer.SerializationException: cannot serialize unregistered type: class io.atomix.copycat.server.request.PollRequest
        at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:589) ~[rafty-server-1.0-SNAPSHOT.jar:na]
        at io.atomix.catalyst.transport.NettyConnection.writeRequest(NettyConnection.java:180) ~[rafty-server-1.0-SNAPSHOT.jar:na]
        at io.atomix.catalyst.transport.NettyConnection.lambda$send$11(NettyConnection.java:295) ~[rafty-server-1.0-SNAPSHOT.jar:na]
        at io.atomix.catalyst.transport.NettyConnection$$Lambda$57/1712713197.run(Unknown Source) ~[na:na]
        at io.atomix.catalyst.util.concurrent.Runnables.lambda$logFailure$17(Runnables.java:20) ~[rafty-server-1.0-SNAPSHOT.jar:na]
        at io.atomix.catalyst.util.concurrent.Runnables$$Lambda$5/1555690610.run(Unknown Source) [rafty-server-1.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
```

**Comment by kuujo** [comment]
We've seen this every now and then. Was this built from `master`?

A little background on what you're seeing: `PollRequest` is a server-to-server request that's typically the first request sent in the cluster. Request types are registered with the `Serializer` via the Java `ServiceLoader` pattern and provided to the `Serializer` via `ServiceLoaderTypeResolver`. Did you do anything to change the `Serializer`? What does the `CopycatServer.Builder` look like, and what do your dependencies look like? I have never been able to reproduce this myself but have seen it come up a few times. There may be some other related issues here or in the [Atomix](http://github.com/atomix/atomix) queue

**Comment by kuujo** [comment]
Alternatively, I would *love* if you could give me a reproducer in a test, gist, or in a throw away GitHub repo. Sure I could find the issue quickly.

Alternatively, the examples are known to work so you can check for differences in dependencies and what not.

**Comment by qinjin** [comment]
Hi 

Thanks! Haven't changed any code in copycat. The code looks like this:

```Java
this.copyCatServer = CopycatServer.builder(this.serverAddress, members)
                .withTransport(new NettyTransport())
                .withStateMachine(new MyStateMachine())
                .withStorage(new Storage(storageDir, StorageLevel.MEMORY))
                .build();
```
The storageDir is: 
```Java
System.getProperty("user.dir") + "/logs/" + serverId
```

The dependency in pom is:
```XML
           <dependency>
                <groupId>io.atomix.copycat</groupId>
                <artifactId>copycat-server</artifactId>
                <version>1.0.0-beta2</version>
            </dependency>
            <dependency>
                <groupId>io.atomix.copycat</groupId>
                <artifactId>copycat-client</artifactId>
                <version>1.0.0-beta2</version>
            </dependency>
            <dependency>
                <groupId>io.atomix.catalyst</groupId>
                <artifactId>catalyst-netty</artifactId>
                <version>1.0.0-rc4</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>18.0</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.1.2</version>
            </dependency>
```
It works fine when I ran code from Intellij, but it threw that SerializationException when I built a jar and executed in local command line.

**Comment by madjam** [comment]
The built copycat jar should contain the resource ```META-INF/services/io.atomix.catalyst.serializer.CatalystSerializable```. Depending on how you are packaging the jar in your setup, it is possible you might be missing this.

**Comment by kuujo** [comment]
Copycat no longer registers serializers via the `ServiceLoader` pattern. All serializer registration is done programmatically. This should no longer be an issue.
